import { Novel, Chapter } from '../types';

export const downloadAsTxt = (filename: string, content: string) => {
  const element = document.createElement("a");
  const file = new Blob([content], { type: 'text/plain' });
  element.href = URL.createObjectURL(file);
  element.download = `${filename.replace(/[^a-z0-9]/gi, '_')}.txt`;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
};

export const exportNovel = (novel: Novel, chapters: Chapter[]) => {
  const sortedChapters = [...chapters].sort((a, b) => a.order - b.order);

  let fullText = `Title: ${novel.title}\n`;
  fullText += `Status: ${novel.status}\n`;
  fullText += `Description: ${novel.description}\n`;
  fullText += `Generated by SK Novel\n\n`;
  fullText += `====================================\n\n`;

  sortedChapters.forEach(chapter => {
    fullText += `Chapter ${chapter.order}: ${chapter.title}\n`;
    fullText += `------------------------------------\n\n`;
    fullText += `${chapter.content}\n\n`;
    fullText += `====================================\n\n`;
  });

  downloadAsTxt(novel.title, fullText);
};

export const exportChapter = (novelTitle: string, chapter: Chapter) => {
  const header = `${novelTitle} - ${chapter.title}\n\n`;
  downloadAsTxt(`${novelTitle}_Ch${chapter.order}`, header + chapter.content);
}